---
- name: docker purpose
  hosts: docker_slaves
  become: yes
  become_method: sudo
  tasks:
    - name: to login to aws ECR
      shell: $(aws ecr get-login --no-include-email)

    - name: pull docker image
      shell: docker push 540368896160.dkr.ecr.us-east-2.amazonaws.com/app1:latest

    - name: to start docker con
      shell: docker run --name con1 -itd -p 8080:8080 540368896160.dkr.ecr.us-east-2.amazonaws.com/app1:latest
